# Generated by Django 5.1.1 on 2024-11-06 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='comment',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
